---
# This file tells pre-commit which hooks are provided by this repo

- id: clazy
  name: clazy
  entry: hurzelchen-clazy
  description: KDE/clazy - Qt-oriented static code analyzer based on the Clang framework
  types_or: [c++]
  language: python
- id: include-what-you-use
  name: include-what-you-use
  entry: hurzelchen-include-what-you-use
  description: Runs Include-What-You-Use (iwyu) on C/C++ code
  types_or:  [c, c++, c#, objective-c, cuda]
  language: python
